[project]
name = "aiolimq"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "asynciolimiter>=1.2.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
]
